//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace BCIT_Textbook_Sale.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Posting
    {
        public int Id { get; set; }
        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 2)]
        [DataType(DataType.Text)]
        [Display(Name = "Title")]
        public string title { get; set; }

        public string username { get; set; }
        public System.DateTime postdate { get; set; }

        [Required]
        [StringLength(1000, ErrorMessage = "The {0} can not be empty.", MinimumLength = 1)]
        [Display(Name = "Detail")]
        public string description { get; set; }

        [Required]
        [Display(Name = "Program ID")]
        public string programID { get; set; }

        [Required]
        [Display(Name = "Buy/Sell")]
        public string postingType { get; set; }

        [Display(Name = "img link")]
        public string imglink { get; set; }
    
        public virtual Program Program { get; set; }
    }
}
