//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCIT_Textbook_Sale.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Posting
    {
        public int Id { get; set; }
        public string title { get; set; }
        public string username { get; set; }
        public System.DateTime postdate { get; set; }
        public string description { get; set; }
        public string programID { get; set; }
        public string postingType { get; set; }
        public string imglink { get; set; }
        public Nullable<decimal> price { get; set; }
    
        public virtual Program Program { get; set; }
    }
}
